# Generated by Django 5.2.5 on 2025-11-21 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True)),
                ('endereco', models.CharField(max_length=225)),
                ('telefone', models.CharField()),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
    ]
