# Generated by Django 5.2.5 on 2025-11-09 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamentos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agendamento',
            name='atualizaado_em',
        ),
        migrations.AddField(
            model_name='agendamento',
            name='atualizado_em',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
